### ISSUE TITLE
Closed

### ISSUE THREAD

**Issue by fjanes-at-amadeus-dot-com** [SmartBear/cucumberstudio-issue-tracker#142]

**Comment by aurelien-reeves** [comment]
Hi,

Recent updates of Hiptest On-premises may requires the Jira Server Add-on to be configured again.

Could you please go to your Jira Add-on management page to check and re-configure the Hiptest add-on as explained here: https://hiptest.com/docs/configure-jira-with-hiptest-on-premises/ ?

Also I invite you to contact us directly at support@hiptest.com if this is possible for you.

Regards,
Aurélien

**Comment by fjanes-at-amadeus-dot-com** [comment]
All set now.
Thank you.
