### ISSUE TITLE
Organizations projects page / member user / can see project names they are not members of

### ISSUE THREAD

**Issue by fjanes-at-amadeus-dot-com** [SmartBear/cucumberstudio-issue-tracker#146]
### Steps to reproduce
1. Have an organization with multiple projects
2. Have a member user only in one project
3. On the project page, note the member only sees the projects they are member of

### Expected behaviour
To be advised

### Actual behaviour
On the organization project page, note the member sees project names they are NOT a current member of

### My configuration
Firefox 60.0.2

**Operating system:**
Windows 7 Enterprise
[Hiptest - On the organizations projects page, a member user can see the project names they are not also members of .docx](https://github.com/hiptest/hiptest-issue-tracker/files/2119743/Hiptest.-.On.the.organizations.projects.page.a.member.user.can.see.the.project.names.they.are.not.also.members.of.docx)

**Comment by aurelien-reeves** [comment]
Hi,

The described behavior is the expected one.
We have an incoming feature where users may use this page to request access to projects.

**Comment by fjanes-at-amadeus-dot-com** [comment]
CONFIDENTIAL & RESTRICTED
@ Aurélien

Hmmm, so if we extend a user to a customer in a shared project,
then they can see other customer projects (by name), and we may not want that.

So I am assuming the only alternative is to make separate organization projects ?

Regards,
Franc / QA


Franc Janes<https://rndwww.nce.amadeus.net/confluence/pages/viewpage.action?spaceKey=~fjanes&title=Franc+Janes>
Senior Quality Assurance Engineer<https://www.istqb.org/downloads/send/5-agile-tester-extension-documents/41-agile-tester-extension-syllabus.html>
AIR-AME-DGA-DGS-EQA<https://rndwww.nce.amadeus.net/confluence/display/RNDSEEDDSNOA/AIR-AME-DGA-DGS-EQA>

Amadeus<http://www.amadeus.com/web/amadeus/en_1A-corporate/Airlines/Airline-Systems/Digital-and-Direct-Retailing-Systems/Digital/1400000042013-Categorizable_P-AMAD_CategoryDetailPpal-1319637765587?industrySegment=1259068355670>
1050 Winter St<https://www.google.com/maps/place/1050+Winter+St,+Waltham,+MA+02451/@41.6121303,-77.2169316,6.5z/data=!4m5!3m4!1s0x89e39c962bfc20bd:0x8caf057128139a0a!8m2!3d42.4074723!4d-71.2768829>
Waltham<http://www.city.waltham.ma.us/> MA<http://www.mass.gov/portal/> 02451<https://tools.usps.com/go/ZipLookupResultsAction!input.action?resultMode=2&companyName=&address1=&address2=&city=&state=Select&urbanCode=&postalCode=02451&zip=>
USA<https://www.usa.gov/federal-agencies/a>

1-781-522-8912<https://en.wikipedia.org/wiki/Area_codes_781_and_339>
1-888-815-0806   (3, 7120 8912, 1)<https://en.wikipedia.org/wiki/Toll-free_telephone_numbers_in_the_North_American_Numbering_Plan>

fjanes@amadeus.com<mailto:fjanes@amadeus.com>

[cid:image001.png@01D235C4.15B21460]<http://www.amadeus.com/>

**Comment by fjanes-at-amadeus-dot-com** [comment]
CONFIDENTIAL & RESTRICTED
Not sure if you get the reply.
Also forwarding to support@hiptest.net

**Comment by aurelien-reeves** [comment]
After discussion with the product owner, indeed your request is legitimate.

Thank you for your feedback!

Regards,
Aurélien

**Comment by fjanes-at-amadeus-dot-com** [comment]
CONFIDENTIAL & RESTRICTED


@ Aurélien

Great, many thanks for the review.
If/when you have a target date for a fix, that would be good to know.

We don’t want to use multiple projects in one organization where a customer member user could view the names of other projects.

Regards,
Franc / QA


Franc Janes<https://rndwww.nce.amadeus.net/confluence/pages/viewpage.action?spaceKey=~fjanes&title=Franc+Janes>
Senior Quality Assurance Engineer<https://www.istqb.org/downloads/send/5-agile-tester-extension-documents/41-agile-tester-extension-syllabus.html>
AIR-AME-DGA-DGS-EQA<https://rndwww.nce.amadeus.net/confluence/display/RNDSEEDDSNOA/AIR-AME-DGA-DGS-EQA>

Amadeus<http://www.amadeus.com/web/amadeus/en_1A-corporate/Airlines/Airline-Systems/Digital-and-Direct-Retailing-Systems/Digital/1400000042013-Categorizable_P-AMAD_CategoryDetailPpal-1319637765587?industrySegment=1259068355670>
1050 Winter St<https://www.google.com/maps/place/1050+Winter+St,+Waltham,+MA+02451/@41.6121303,-77.2169316,6.5z/data=!4m5!3m4!1s0x89e39c962bfc20bd:0x8caf057128139a0a!8m2!3d42.4074723!4d-71.2768829>
Waltham<http://www.city.waltham.ma.us/> MA<http://www.mass.gov/portal/> 02451<https://tools.usps.com/go/ZipLookupResultsAction!input.action?resultMode=2&companyName=&address1=&address2=&city=&state=Select&urbanCode=&postalCode=02451&zip=>
USA<https://www.usa.gov/federal-agencies/a>

1-781-522-8912<https://en.wikipedia.org/wiki/Area_codes_781_and_339>
1-888-815-0806   (3, 7120 8912, 1)<https://en.wikipedia.org/wiki/Toll-free_telephone_numbers_in_the_North_American_Numbering_Plan>

fjanes@amadeus.com<mailto:fjanes@amadeus.com>

[cid:image001.png@01D235C4.15B21460]<http://www.amadeus.com/>

**Comment by cbliard** [comment]
Beaucoup de pistes d'implémentation possibles. À réfléchir concernant l'implémentation.

**Comment by fjanes-at-amadeus-dot-com** [comment]
Issue was filed for JIRA Hiptest, which we are no longer using.
