### ISSUE TITLE
Help on ActionWordLibrary missing

### ISSUE THREAD

**Issue by ylacaute** [SmartBear/cucumberstudio-issue-tracker#200]
Hi,

I am still playing with HipTest for my company, and I am not satisfy about the default generated java code (for example, all ActionWords are generated in a single class, that will be a nightmare later). So I am starting to override hbs templates... and I have discovered "ActionWordLibrary".

Indeed, in the publisher java templates, I found few templates dealing with "ActionWordLibrary" but I didn't find any help on it, what are ActionWordLibrary ? How to use them ? I have the feeling that could be an alternative to override hbs templates.

Thanks

**Comment by TimotheeVille** [comment]
Hi,
Sorry for this late answer.

ActionwordLibrary is used for sharing actionwords between different projects of the same organization. (Beta feature) The idea behind is the same (grouping actionwords) but I'm not sure you will be able to use it to split your actionwords into different files.
I think you are on the right way to do what you wish, overriding templates is the most efficient way to do it!

Hope it can helps
