### ISSUE TITLE
Rename everywhere action does not work (and gives no error) when action word already exists

### ISSUE THREAD

**Issue by makakk** [SmartBear/cucumberstudio-issue-tracker#218]
### Steps to reproduce
1. Click on an action word in the existing scenario
2. Change the action word to any of the existing ones
3. Choose ACTION "Rename everywhere"

### Expected behaviour
Error visible only in DevTools/Network: "An action word with name 'name_of_action_word' already exists" should be presented to the user.

### Actual behaviour
Nothing happens, action word is not changed to the desired one, error message is not presented to the user (visible in DevTools/Network only).
![2020-05-04 17_45_55-](https://user-images.githubusercontent.com/14992672/80985290-4fb39e00-8e2f-11ea-8ecd-a040fc620b22.png)

### My configuration
**Browser:**
Chrome 81.0.4044.129 x64

**Operating system:**
Win10 Pro x64

**Comment by TimotheeVille** [comment]
Hi,
Thank your for having reporting this bug :smile:, we already opened a ticket internally. We will keep you in touch here.
