### ISSUE TITLE
cant login 

### ISSUE THREAD

**Issue by TalyGliksmanVia** [SmartBear/cucumberstudio-issue-tracker#220]
Steps to reproduce
1.try to login 
2.get your log out pop-up

**Comment by aurelien-reeves** [comment]
Hi,

Thanks for the report.
Indeed, it seems there is something wrong. We take a look on that right now

You can follow our status page on https://cucumber.statuspage.io/ to be notified as soon as it is fixed

**Comment by aurelien-reeves** [comment]
A fix has been deployed. You should be able to login now.

Sorry for the inconvenience
