### ISSUE TITLE
Uploading feature files with two Scenario Outlines do not create datatable entries

### ISSUE THREAD

**Issue by mschmieder** [SmartBear/cucumberstudio-issue-tracker#221]
### Steps to reproduce
1. Create a simple `BDD-friendly` project and upload the following feature file

```feature
Feature: Provide Plan Info

    Scenario Outline: Create Plan
        Given the "<user>" is logged in
        And the case "myCase" exists
        And the plan "<plan>" is in status "Created"

        Examples:
            | user  | plan |
            | user1 | 1    |
            | user2 | 2    |
            | user3 | 3    |
            | user4 | 4    |


    Scenario Outline: Update Plan
        Given the "<user>" is logged in
        And the case "myCase" exists
        And the plan "<plan>" is in status "Updated"

        Examples:
            | user  | plan |
            | user1 | 1    |
            | user2 | 2    |
            | user3 | 3    |
            | user4 | 4    |
```

### Expected behaviour
Two Scenarios should have been created with the respective `Example` tables correctly set

### Actual behaviour
Instead of setting the datatable entries, the tables of both scenarios are empty. This also happens if I create them manually, download the feature file from CucumberStudio and try to upload them again

Uploading the feature file with only one Scenario Outline works fine.
### My configuration
**Browser:**
Safari

**Operating system:**
MacOS
![Screenshot 2020-06-13 at 14 06 50](https://user-images.githubusercontent.com/16526092/84568410-a477fc00-ad7f-11ea-8ea9-b69adf440b16.png)
![Screenshot 2020-06-13 at 14 07 06](https://user-images.githubusercontent.com/16526092/84568412-a772ec80-ad7f-11ea-9a51-b877bc22d21d.png)
![Screenshot 2020-06-13 at 14 07 18](https://user-images.githubusercontent.com/16526092/84568414-aa6ddd00-ad7f-11ea-8390-f573f10d40b1.png)
![Screenshot 2020-06-13 at 14 07 26](https://user-images.githubusercontent.com/16526092/84568416-ad68cd80-ad7f-11ea-931d-b7709c671983.png)

**Comment by HoudaDabou** [comment]
Hi!

Thanks for the bug report :+1: 

We're going to create a ticket internally to fix this issue ASAP.

In the meantime, you can either use the drag and drop feature to import your feature file(s), or the "Update feature from Git" option to achieve this:

![feature_drag drop](https://user-images.githubusercontent.com/43133237/84948152-97466e80-b0eb-11ea-811d-8a9bad5aeca3.png)



We'll keep you posted on the deployment of the fix.

**Comment by HoudaDabou** [comment]
Hi @mschmieder,

Our team has deployed a patch to solve this issue, thanks again for your bug report :+1:
