### ISSUE TITLE
Cloned BDD-friendly project displays as Classic on Dashboard

### ISSUE THREAD

**Issue by janpollak** [SmartBear/cucumberstudio-issue-tracker#222]
### Steps to reproduce
1. Clone BDD-friendly project
2. New project is created but displays as Classic on Dashboard, though its "Automation Ready (BDD mode)" switch in Settings is on

### Expected behaviour
Cloned BDD-friendly project would display as Classic on Dashboard

### Actual behaviour
Cloned BDD-friendly project displays as Classic on Dashboard

### My configuration
**Browser:** Safari – 13.1.1

**Operating system:** macOS Catalina – 10.15.5

**Comment by DavidL06** [comment]
Hello, this is being resolved at the moment. We will let you know when it is fixed.

**Comment by DavidL06** [comment]
@janpollak It should be fixed now. Could you confirm that?

**Comment by janpollak** [comment]
@DavidL06 Works good now. Thanks a lot!
