### ISSUE TITLE
API routes for removing tests from a test-run missing?

### ISSUE THREAD

**Issue by mschmieder** [SmartBear/cucumberstudio-issue-tracker#225]
### Steps to reproduce
Hello there, 
I do not seem to be able to figure out the process of updating a test-run using the provided APIs. At least within the UI it is possible to remove single tests and add tests to a test-run.

Currently I do the following:
- Get a specific test run using `https://studio.cucumber.io/api/projects/<project_id>/test_runs/<test_run_id>`
- Retrieving the test folders for this test run with `https://studio.cucumber.io/api/projects/<project_id>/test_runs/<test_run_id>/folder_snapshots` including the `children` and `test-snapshots`

These show me the wanted IDs but I cannot seem to figure out how to remove them from the folder.
Looking at the UI routes it seems there should be something like `scenario-snapshots` but I don't see a way to get them with the API

### Expected behaviour
Ability to add/remove tests to a test run

### Actual behaviour
n/a

**Comment by HoudaDabou** [comment]
Hi,

Actually, you're only able to [add one scenario](https://studio-api.cucumber.io/#add-a-scenario-to-an-existing-test-run) or [add multiple scenarios](https://studio-api.cucumber.io/#add-multiple-scenarios-to-an-existing-test-run) in an existing test run.

Currently there is no API endpoint to delete a test snapshot from a test run.It's a feature request!

**Comment by mschmieder** [comment]
> Actually, you're only able to [add one scenario](https://studio-api.cucumber.io/#add-a-scenario-to-an-existing-test-run) or [add multiple scenarios](https://studio-api.cucumber.io/#add-multiple-scenarios-to-an-existing-test-run) in an existing test run.

The weird part it, that your WebGUI seems to be able to issue REST calls to do it...so maybe you did not expose all endpoints to us customers?

**Comment by HoudaDabou** [comment]
We develop the API endpoints according to the needs of our clients and our current priorities.

Anyway, the API endpoint to delete a test has been deployed :slightly_smiling_face: 

Here is the endpoint: https://studio-api.cucumber.io/#delete-a-test

**Comment by mschmieder** [comment]
Nice! Thanks a lot. I'll have a try and see if I can solve my logic with the provided API extension.
