### ISSUE TITLE
Tags not included in Scenarios exports through the API

### ISSUE THREAD

**Issue by mzajicekFB** [SmartBear/cucumberstudio-issue-tracker#228]
### Steps to reproduce
1. Create test scenarios with tags in a project
2. Setup Headers for Cucumber API in Postman for the Scenarios export endpoint https://studio.cucumber.io/api/projects/206792/scenarios
![image](https://user-images.githubusercontent.com/69979441/90794621-43cfe700-e30d-11ea-9603-cd66f75b8766.png)

3.Set include to "tags"
4.Send request

### Expected behaviour
The tags should be included in the body of the response. 
FYI : i'm trying to get the tags since i put there the id of requirements covered by each scenario in order to create a requirement coverage matrix. Maybe there's a better way to do this...

### Actual behaviour
Tags values are empty for each scenario : 
![image](https://user-images.githubusercontent.com/69979441/90794983-cbb5f100-e30d-11ea-90cd-07975c20b082.png)

### My configuration
**Postman**
**Windows 10**
**Headers**
![image](https://user-images.githubusercontent.com/69979441/90794894-ac1ec880-e30d-11ea-8ead-8aea903fb0ad.png)

**Comment by mzajicekFB** [comment]
PEBKAC : the include must be set as parameter of the request, not in the headers.

**Comment by cbliard** [comment]
Thanks for finding that out. Can you let us know which documentation you were looking at? There may be something to improve here to make it more obvious.

**Comment by mzajicekFB** [comment]
I was looking at this page : https://studio-api.cucumber.io/#tags and then the JSON API syntax. But i didn't read through correctly though. IMO it's clear enough. 
FYI, credits to Houda for helping me finding that out.

**Comment by cbliard** [comment]
Perfect, thanks :)
