### ISSUE TITLE
Recherche combinée dans les Features

### ISSUE THREAD

**Issue by Natacha-Adrien** [SmartBear/cucumberstudio-issue-tracker#240]
### Étapes à reproduire
1. Aller sur le menu "Features"
2. Saisir une recherche combinée sur des tags

### Comportement prévisible
Les scénarios avec les reherches combinées apparaissent.

### Comportement réel
La combinaison n'est pas prise en compte.
Est-ce une mauvaise utilisation de notre part ? Comment combiner une recherche sur des tags ?

### Ma configuration
** Navigateur: Chrome
** Système opérateur: Windows 10 Professionnel
![RechercheHiptest](https://user-images.githubusercontent.com/92514248/137292289-8bcbcc08-0bb6-4ef7-aca6-7f013e181826.JPG)

**Comment by Natacha-Adrien** [comment]
Bonjour HoudaDabou,
Nous sommes en version 3.6.3.0 et avec seulement l'espace, la recherche combinée ne fonctionne pas correctement.

**Comment by HoudaDabou** [comment]
Merci @Natacha-Adrien pour cette précision.

J'ai effectué un test sur la dernière version `3.6.4.0` et le résultat de la recherche semble correct. 
Les deux versions, `3.6.3.0` et  `3.6.4.0`, ne comportent aucune mise à jour du code à ce niveau, d'après mes connaissances.

 Afin de nous permettre d'analyser ce problème, pouvez-vous refaire une recherche en capturant le `header` et la `response` de la requête depuis le `Network`, comme ci-après : 
![csonprem_search](https://user-images.githubusercontent.com/43133237/149555246-cec6763e-3aff-492f-bb8a-fdb4e0468b61.png)

Merci de nous transmettre ces éléments par email à studio@cucumber.io 

Un ticket en interne a été ouvert, référence #BDD-385, je vous invite donc à continuer cette conversation en privé.
