### ISSUE TITLE
Issue with loading of test steps in Background section [Bug]

### ISSUE THREAD

**Issue by anshulkansal** [SmartBear/cucumberstudio-issue-tracker#243]
### Steps to reproduce
1. Go to any section
2. Click on Background
3. No Background test steps visible

### Expected behaviour
Background Test steps should be visible.

### Actual behaviour
Need to refresh the page to load background test steps.

### My configuration
**Browser:** Chrome Version 96.0.4664.93 (Official Build) (64-bit)

**Operating system:** Windows 10 Pro

**Comment by HoudaDabou** [comment]
Hi!

Thanks for the bug report :+1: 

An internal support ticket, reference #BDD-366,  has been opened to fix it ASAP.

To temporarily overcome this issue, please reload the CucumberStudio page so that you'll be able to see and update the 'Background' section.

**Comment by anshulkansal** [comment]
Hi,

Any ETA on this issue?

**Comment by HoudaDabou** [comment]
Hey @anshulkansal,

Good news, a fix was deployed a few minutes ago. Please reload the page to see the changes.

Thanks again for the bug report!

**Comment by anshulkansal** [comment]
Thanks @HoudaDabou
