### ISSUE TITLE
Double quotes are missing for steps (API "Get tests of a test run" route)

### ISSUE THREAD

**Issue by TomLaVachette** [SmartBear/cucumberstudio-issue-tracker#244]
### Steps to reproduce
1. Create a test run by using the route or the dashboard.
2. Get tests of a test run with [this route](https://studio-api.cucumber.io/#get-tests-of-a-test-run).

### Expected behaviour
Get all steps with double quotes.
`{ "action": "And he filters refurbished offers by \"Parfait état\"" },`

### Actual behaviour
Double quotes are removed from the response, resulting in unknown steps.
`{ "action": "And he filters refurbished offers by Parfait état" },`

**Comment by HoudaDabou** [comment]
Hi @TomLaVachette,

After checking, it seems that returning the parameters values without double quotes, is the desired behaviour.

If you want to get the behaviour that you expected, you should add a step to your actionword definition as an Action or a Result which include a parameter using this ${variable} format.

Let's take a quick example to explain this, here, each actionword has a parameter:
![sc_twoaws](https://user-images.githubusercontent.com/43133237/149531606-a97e5784-5232-4c39-a850-ea8df175d4e3.png)

The difference is their definition, this actionword has a result step including the ${variable} format as a definition:

![aw_def_result](https://user-images.githubusercontent.com/43133237/149532485-79773d89-8857-4087-9aca-bbe445c55d82.png)

The second actionword has no definition:
![aw_no_def](https://user-images.githubusercontent.com/43133237/149540119-4de162e0-c903-4931-b815-43c5edc2a69d.png)

And the tests view of the scenario looks like this:

![viewtests_sc](https://user-images.githubusercontent.com/43133237/149540262-821fb716-38e2-4a05-b91a-a7adec11ca43.png)

As you see, ${message} value is defined as a dataset and will be returned via the API like this: `{ "result": "Displayed message is \"Ready\"" }`

So adding a step definition to your actionword that implements the [${variable} syntax](https://support.smartbear.com/cucumberstudio/docs/tests/datatable.html) could address your need. WDYT?

**Comment by HoudaDabou** [comment]
I'm going to close this issue, feel free to email us at: studio@cucumber.io for any further assistance!
