### ISSUE TITLE
Not able to change the execution test status 

### ISSUE THREAD

**Issue by gjprasad** [SmartBear/cucumberstudio-issue-tracker#245]
### Steps to reproduce
1. Click existing test cases in test run
2. Try to change the execution test status and the option was grad-out

### Expected behaviour
User should change the execution test status into Passed/Failed/Not run ..etc

### Actual behaviour
The option is fully grad-out

### My configuration
Chrome

**Operating system:**
Windows 10
![Hiptest_testrun](https://user-images.githubusercontent.com/43351118/147202092-cb81c6f2-f126-4c99-92d8-eb97f9b78619.jpg)

**Comment by HoudaDabou** [comment]
Hi @gjprasad,

Actually, you can't update the test results when the execution cycle (build) is closed. You should open a new one by clicking on 'Start test', then you'll be able to start a new manual tests execution.

We can reopen it if you want, however, your issue requires an investigation in depth. 

Could you please contact us via the in-app chat or by email at: studio@cucumber.io ?
